  name: Backport

  on:
    pull_request:
      types: labeled
      branches:
      - master

  jobs:
    backport:
      runs-on: ubuntu-latest
      steps:
      - uses: hmharvey/act-on-label@master
        with:
          labels: 'backport'
      - uses: actions/checkout@v1.1.0
        with:
          ref: 'stable-branch'
      - id: cherry-pick
        uses: hmharvey/cherry-pick-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.cherry-pick.outputs.branch_name }}
          destination_branch: 'stable-branch'
